#!/bin/bash

# Update the last loaded date....

update_path="$HOME/Library/Application Support/Homebrew"
mkdir -p "${update_path}"
last_update="${update_path}/last_update.txt"

touch "$last_update"

echo Brew previous updated at $(cat "$last_update").

sleep 2

echo "-----  Updating...  -----" &&
brew update &&
sleep 2 &&
echo "-----  Upgrading...  -----" &&
brew -v upgrade  &&

echo ----- Cleanup old installs ----- &&
brew cleanup


# htop needs root permissions to work properly and I prefer this method to 
# using sudo every time I run htop.  

if [ ! -u /usr/local/Cellar/htop/*/bin/htop ] ; then
    sudo chmod -v u+s /usr/local/Cellar/htop/*/bin/htop
fi

if [ -O /usr/local/Cellar/htop/*/bin/htop ] ; then
    sudo chown -v root /usr/local/Cellar/htop/*/bin/htop
fi

echo $(date) > "${last_update}"
echo Brew updated as of $(cat "$last_update").
