#!/bin/bash

cronfile=$HOME/crontab.$HOSTNAME.$(date +"%F_%T" --utc)

crontab -l > $cronfile

MESSAGE="# crontab disabled.  To restore, run the following\n# crontab $cronfile" 

echo -e $MESSAGE |crontab

echo -e $MESSAGE
